---
project_name: "example"
time_start: 12/02/2024
time_end: 12/04/2024
instances:
  - id: 1
    vm_lot_name: "example-a"
    network: "x.x.x.x/24"
    vlan: 2237
    count: 1
    start_at: 10
    spec:
      memory: 8192
      vcpu: 2
      disk: 60
  - id : 2
    vm_lot_name: "example-a"
    network: "x.x.x.x/24"
    vlan: 2237
    count: 80
    start_at: 80
    spec:
      memory: 4096
      vcpu: 1
      disk: 40