---
project_name: "test"
time_start: 12/02/2024
time_end: 12/04/2024
time_delete: 12/05/2024
proxmox_ip: 172.16.129.101
template_id: 9000
instances:
  - id: 1
    vm_lot_name: "test-a"
    network: "172.16.239.0/24"
    vlan: 2239
    count: 2
    start_at: 10
    spec:
      memory: 8192
      vcpu: 2
      disk: 60